language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=announcementcenter
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list
  - ./occ app:enable $APP_NAME
  - ./occ app:list

script:
  - cd apps/$APP_NAME/
  - ../../build/composer.phar install
  - vendor/bin/parallel-lint  --exclude vendor .
  - vendor/bin/php-cs-fixer fix --allow-risky yes --dry-run -v --diff --diff-format udiff

  # Test the app
  - cd ../../
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests/
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then ../../../lib/composer/bin/phpunit --configuration phpunit.xml; fi"

  # Create coverage report
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  - cd ../

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=pgsql
    - php: 7.2
      env: DB=mysql  
    - php: 5.6
      env: DB=mysql CODECHECK=1
    - php: 5.6
      env: DB=mysql CODECHECK=2
    - php: 7.1
      env: DB=mysql CORE_BRANCH=master
    - php: 7.2
      env: DB=pgsql CORE_BRANCH=master
  allow_failures:
    - env: DB=mysql;CODECHECK=2
  fast_finish: true
